apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-challenge
  labels:
    app: code-challenge
spec:
  replicas: 2
  selector:
    matchLabels:
      app: code-challenge
  template:
    metadata:
      labels:
        app: code-challenge
    spec:
      containers:
      - image: localhost:5000/code-challenge
        imagePullPolicy: Always
        name: code-challenge
        ports:
        - containerPort: 8080